### ISSUE TITLE
make failed on Ubuntu 15.10

### ISSUE THREAD

**Issue by kaneawk** [sultanqasim/android_kernel_motorola_msm8916#10]
`Warning (ranges_format): /soc/qcom,pm@8600664 has empty "ranges" property but its #address-cells (2) differs from /soc (1)
make[1]: Leaving directory '/home/kaneawk/src/android/omni-twrp-tree/kernel/motorola/msm8916'
make  -C kernel/motorola/msm8916 O=/home/kaneawk/src/android/omni-twrp-tree/out/target/product/merlin/obj/KERNEL_OBJ ARCH=arm CROSS_COMPILE=" arm-eabi-" modules
make[1]: Entering directory '/home/kaneawk/src/android/omni-twrp-tree/kernel/motorola/msm8916'

The present kernel configuration has modules disabled.
Type 'make config' and enable loadable module support.
Then build a kernel with module support enabled.

/home/kaneawk/src/android/omni-twrp-tree/kernel/motorola/msm8916/Makefile:1036: recipe for target 'modules' failed
make[2]: **\* [modules] Error 1
Makefile:139: recipe for target 'sub-make' failed
make[1]: **\* [sub-make] Error 2
make[1]: Leaving directory '/home/kaneawk/src/android/omni-twrp-tree/kernel/motorola/msm8916'
build/core/tasks/kernel.mk:222: recipe for target 'TARGET_KERNEL_BINARIES' failed
make: [TARGET_KERNEL_BINARIES] Error 2 (ignored)
make  -C kernel/motorola/msm8916 O=/home/kaneawk/src/android/omni-twrp-tree/out/target/product/merlin/obj/KERNEL_OBJ INSTALL_MOD_PATH=../../system ARCH=arm CROSS_COMPILE=" arm-eabi-" modules_install
make[1]: Entering directory '/home/kaneawk/src/android/omni-twrp-tree/kernel/motorola/msm8916'

The present kernel configuration has modules disabled.
Type 'make config' and enable loadable module support.
Then build a kernel with module support enabled.

/home/kaneawk/src/android/omni-twrp-tree/kernel/motorola/msm8916/Makefile:1036: recipe for target 'modules_install' failed
make[2]: **\* [modules_install] Error 1
Makefile:139: recipe for target 'sub-make' failed
make[1]: **\* [sub-make] Error 2
make[1]: Leaving directory '/home/kaneawk/src/android/omni-twrp-tree/kernel/motorola/msm8916'
build/core/tasks/kernel.mk:222: recipe for target 'TARGET_KERNEL_BINARIES' failed
make: [TARGET_KERNEL_BINARIES] Error 2 (ignored)
mdpath=`find /home/kaneawk/src/android/omni-twrp-tree/out/target/product/merlin/system/lib/modules -type f -name modules.order`; if [ "$mdpath" != "" ];then mpath=`dirname $mdpath`; ko=`find $mpath/kernel -type f -name *.ko`; for i in $ko; do arm-eabi-strip --strip-unneeded $i; mv $i /home/kaneawk/src/android/omni-twrp-tree/out/target/product/merlin/system/lib/modules/; done; fi
mdpath=`find /home/kaneawk/src/android/omni-twrp-tree/out/target/product/merlin/system/lib/modules -type f -name modules.order`; if [ "$mdpath" != "" ];then mpath=`dirname $mdpath`; rm -rf $mpath; fi
`

**Comment by sultanqasim** [comment]
I have kernel modules disabled in the defconfigs I use for building TWRP. TWRP doesn't use kernel modules, so I disable them to reduce kernel size. Running make modules when kernel modules are disabled will fail. On my machine, it ignores this error in the TWRP build process. If your build process is insistent on building modules, you can always change the defconfig and enable CONFIG_MODULES.
