### ISSUE TITLE
build breakage with neon/simd

### ISSUE THREAD

**Issue by sthalik** [sultanqasim/android_kernel_motorola_msm8916#2]
Build breakage when used with cm12.1 build system:

<pre>
/root/android/kernel/motorola/msm8916/arch/arm/crypto/sha1_neon_glue.c:30:22: fatal error: asm/simd.h: No such file or directory
 #include &lt;asm/simd.h&gt;
                      ^
compilation terminated.
/root/android/kernel/motorola/msm8916/scripts/Makefile.build:308: recipe for target 'arch/arm/crypto/sha1_neon_glue.o' failed
</pre>

**Comment by sultanqasim** [comment]
Hmm, this fixed it in the standalone build: https://github.com/sultanqasim/android_kernel_motorola_msm8916/commit/5ce2016e6c51ba343a656cbba303ee769acef3aa

I'll take a look at CM build when I get time. If you want to build in the interim, you can disable the optimized NEON SHA implementation in the defconfig.

**Comment by sthalik** [comment]
Hint: it builds with a different build directory. That is, O= for kernel makefile. Take your time, and thanks for the work.

**Comment by sthalik** [comment]
On another note, could you please add boot.img creation targets to standalone build?

**Comment by sultanqasim** [comment]
I used to have a boot.img target in the standalone build (look back a couple months in history), but I removed it when I switched to generating the boot.img at install time in the flashable zip. The boot.img target was cumbersome because I needed to keep updating the ramdisk contents to keep up with the ROM, and the ramdisk contents (init binary, init scripts etc) didn't really belong in the kernel tree.

**Comment by sultanqasim** [comment]
I just tried a build with an external output directory specified with O= and it seemed to build fine. I'll check CM building tomorrow.

Did you try a clean build? The aforementioned (simd.h) header is put in place by a header target in a makefile. I don't know if the build system is smart enough to add the missing header after an older headers target has already been built. If you haven't tried, a clean build might fix your issue.

**Comment by sthalik** [comment]
Yes, I've run mrproper. It's in generated/ just fine.

**Comment by sthalik** [comment]
On another note undervolt really helps the screen not get hot. Great work.
